### ISSUE TITLE
Візуалізатор на головній Рада4ю.орг

### ISSUE THREAD

**Issue by bohemka** [OPORA/visrada4you#3]
Уже писала раніше про тест і тут продублюю. Як на мене, вркай доречно, щоб візуалізатор був прикучений безпосередньо до Rada4you/org - щоб на нього можна було перейти з сайту

**Comment by lisoffsky** [comment]
@beastie87 давай на нього ось туй лінка поставим. 
![image](https://cloud.githubusercontent.com/assets/14181306/25195776/5b57d644-2547-11e7-8e24-4bfe570f049c.png)
назвемо "Візуалізатор даних"

**Comment by bohemka** [comment]
Так, давайте. і вкладку на тести треба поставити

**Comment by beastie87** [comment]
This issue was moved to OPORA/publicwhip#250
