### ISSUE TITLE
биті json, csv посилання

### ISSUE THREAD

**Issue by GS-0001** [OPORA/visrada4you#6]
бите json посилання (для графіку **Консолідованість фракцій в політиці**) напр,
**json:**
>http://vis.rada4you.org/visial/consolidation.json?policy_id=%D0%97%D0%B0+%D0%B1%D1%8E%D0%B4%D0%B6%D0%B5%D1%82+2017

**csv:**
> http://vis.rada4you.org/visial/consolidation.csv?policy_id=%D0%97%D0%B0+%D0%BF%D1%96%D0%B4%D1%82%D1%80%D0%B8%D0%BC%D0%BA%D1%83+%D1%96%D0%BD%D0%B4%D1%83%D1%81%D1%82%D1%80%D1%96%D0%B0%D0%BB%D1%8C%D0%BD%D0%B8%D1%85+%D0%BF%D0%B0%D1%80%D0%BA%D1%96%D0%B2++

**Comment by beastie87** [comment]
@GS-0001 дякую, я в контолері потіряв вказання формату виводу данних, тобто формат був вказаний але не опрацьований)
It is done!
