### ISSUE TITLE
не працює візуалізатор "Персональна статистика нардепів"

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/visrada4you#7]
Ось про що Василина писала в Слак

![image](https://cloud.githubusercontent.com/assets/14181306/25702078/01ae64d6-30d8-11e7-9f90-f80b05a96a6b.png)

**Comment by beastie87** [comment]
@lisoffsky дякую я зрозумів, скоро поправлю)

**Comment by beastie87** [comment]
@lisoffsky  @bohemka  перевіряйте поправив) 
- Done
